on:
  push:
    branches:
      - main

jobs:
  docker:
    uses: guillaumedsde/qbittorrent-distroless/.github/workflows/docker.yml@master
    with:
      platforms: |
        linux/amd64
        linux/arm/v5
        linux/arm/v7
        linux/arm64/v8
    secrets: inherit